#baseURL = "https://sequix.cn/"
baseURL = "http://23.106.155.216/"
languageCode = "zh-CN"
title = "sequix"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

## 是否开启disqus评论，不要和utteranc同时开启
#disqusShortname = "yourdiscussshortname"

[author]
  name = "sequix"

[params]
  author = "sequix"
  subtitle = "专注于Go语言(golang)、云计算、软件架构、算法等"
  keywords = "golang,go语言,go语言笔记,sequix,博客,软件架构,算法"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、软件架构、算法等"
  busuanzi = false #启用不算子网页统计
  localSearch = true # 启用本地搜索
  #googleAd = "ca-pub-4031353640611810"  #ca-pub-xxxxxxxxxxxxxx

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  #customCSS = ['douban.css', 'other.css']

  # if ['custom.css'], load '/static/css/custom.css' file
  # if ['custom.js'], load '/static/js/custom.js' file
  #customJS = ['douban.js']

  # 是否开启目录，可被每篇文章中的设置覆盖
  toc = true 

## 友情链接，可以多个
#[[params.links]]
#  title = "sequix的博客"
#  name = "sequix的博客"
#  url = "https://www.flysnow.org/"

## 配置 utteranc 评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "sequix/blog"
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[markup]
  ## 代码高亮
  [markup.highlight]
    lineNos = true
    style = "github"

  ## 配置目录层级
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

## 配置网站菜单
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3
