baseURL = "https://sequix.cn/"
#languageCode = ""
title = "sequix"
theme = "maupassant"

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

## 是否开启disqus评论，不要和utteranc同时开启
#disqusShortname = "yourdiscussshortname"

[author]
  name = "sequix"

[params]
  author = "sequix"
  subtitle = "programmer | otaku | straight"
  keywords = "golang,sequix"
  description = "programmer | otaku | straight"
  busuanzi = false # 启用阅读次数统计
  localSearch = true # 启用本地搜索

  # if ['custom.css'], load '/static/css/custom.css' file
  # if ['custom.js'], load '/static/js/custom.js' file
  #customJS = ['douban.js']

  # 是否开启目录，可被每篇文章中的设置覆盖
  toc = true 

## 友情链接，可以多个
[[params.links]]
  title = "sequix's github"
  name = "sequix's github"
  url = "https://github.com/sequix"

## 配置 utteranc 评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "sequix/blog"
  issueTerm = "title"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[markup]
  ## 代码高亮
  [markup.highlight]
    lineNos = true
    style = "github"

  ## 配置目录层级
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

## 配置网站菜单
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3
